### ISSUE TITLE
What is the indexing pipeline doing?

### ISSUE THREAD

**Issue by meanna** [JULIELab/smithsearch#11]
Hello, 

I'm trying to create a document search engine in Python that has similar features to smithsearch.

I could not find information about what the indexing pipeline is doing.
I found something in  descAll/AggregateAnalysisEngine.xml
```
                <node>JCoRe Sentence Annotator</node>
                                
                <node>JCoRe Token Annotator</node>
                                
                <node>ICD10 Gazetteer</node>
```
But it is still not clear to me what each step does or whether it is the whole pipeline.

Could you please explain how the indexing pipeline analyses the documents, step by step?
What final information is sent to Elastic search?

Thanks a lot!

**Comment by khituras** [comment]
Hi,

this is a [UIMA](https://uima.apache.org/) pipeline created with the [JCoRe Pipeline Modules](https://github.com/JULIELab/jcore-pipeline-modules). 
The components used are the components JSDB, JTBD and Lingpipe Gazetteer from [jcore-projects](https://github.com/JULIELab/jcore-projects/) and [jcore-base](https://github.com/JULIELab/jcore-base/). Please open the pipeline using the JCoRe Pipeline Builder CLI to see the exact components.

The Sentence splitter splits the input text into sentences.
The Token Annotator further segments sentences into tokens (words, roughly speaking).
The Gazetteer component recognizes named entities from a dictionary by string matching. This is the crucial step. The dictionary contains word forms and IDs.

Finally - not contained in the AggregateAnalysisEngine but in the complete pipeline - the JCoRe ElasticSearch Indexing component sends the tokens with their recognized entity IDs (if any) to ElasticSearch using the preanalyzed format (see https://github.com/JULIELab/elasticsearch-mapper-preanalyzed). This plugin must be installed in ElasticSearch so that the format can be accepted.

I propose you use a test document and a test dictionary. You won't even need an ElasticSearch server but just set the logger `de.julielab.jcore.consumer.es.ElasticSearchConsumer` to trace level (in `config/logback.xml`). You will get an error with ElasticSearch but the JSON format of the sent data should be printed to the console.

**Comment by meanna** [comment]
Thank you for your explaination.

Where can I find `config/logback.xml` ?

If I run only the indexing pipeline on test documents, I can see the output on the console by configuring `config/logback.xml`, right?

(Should I better open a new issue?)

Thank you!

**Comment by meanna** [comment]
I found `config/logback.xml`.
